---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-automation
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
spec:
  type: ClusterIP
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    - name: websocket
      port: 9001
      targetPort: websocket
      protocol: TCP
  selector:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto

