apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/pvc.yaml
  - manifests/ingress.yaml

images:
  - name: ajnart/homarr
    newName: ghcr.io/ajnart/homarr
    newTag: v0.10.7