apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/pvc.yaml
  - manifests/ingress.yaml
