---
uptime-kuma:
  enabled: true

  image:
    repository: louislam/uptime-kuma
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.21.3-debian"

  ingress:
    enabled: true
    host: uptime-kuma.delisle.me
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
          service:
            name: uptime-kuma
            port:
              number: 3001
