---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard  # running in same namespace as adguard-home

resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/servicemonitor.yaml

commonLabels:
  app.kubernetes.io/instance: adguard-exporter
  app.kubernetes.io/name: adguard-exporter

images:
  - name: ebrianne/adguard-exporter
    # renovate: datasource=github-releases depName=ebrianne/adguard-exporter
    digest: sha256:a60deb7d2409939713749a7170d7ec28c7f242a8c7ee798bfdf6fc23e9e5ece6
