---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unpoller-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  namespace: monitoring
  labels:
    app: unpoller
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unpoller  # target app service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - targetPort: 9130
      path: /metrics
      interval: 15s
