---
# Template for Home Assistant secrets
# After running seal-ha-secrets.sh, this will be created as:
# workload/apps/home-assistant/manifests/sealedsecret-secrets.yaml
#
# The sealed secret will contain:
# - secrets.yaml (mounted at /config/secrets.yaml)
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-secrets
  namespace: home-automation
type: Opaque
data:
  secrets.yaml: BASE64_ENCODED_SECRETS_YAML_HERE

