---
# Template for Google Assistant service account
# After running seal-ha-secrets.sh, this will be created as:
# workload/apps/home-assistant/manifests/sealedsecret-google.yaml
#
# The sealed secret will contain:
# - SERVICE_ACCOUNT.json (mounted at /config/SERVICE_ACCOUNT.json)
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-google
  namespace: home-automation
type: Opaque
data:
  SERVICE_ACCOUNT.json: BASE64_ENCODED_SERVICE_ACCOUNT_JSON_HERE

