apiVersion: v1
kind: ServiceAccount
metadata:
  name: transmission-openvpn
  labels:
    app.kubernetes.io/instance: transmission-openvpn
    app.kubernetes.io/name: transmission-openvpn
    app.kubernetes.io/version: "4.0"
