---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

namespace: default

resources:
  # renovate: datasource=github-releases depName=squat/generic-device-plugin
  - https://raw.githubusercontent.com/squat/generic-device-plugin/main/manifests/generic-device-plugin.yaml
  - https://raw.githubusercontent.com/squat/generic-device-plugin/main/manifests/podmonitor.yaml
images:
  - name: ghcr.io/squat/generic-device-plugin
    newTag: 7f23e30a01dbb549faa2f6672f2a85975490da5f
commonLabels:
  app.kubernetes.io/name: generic-device-plugin
  app.kubernetes.io/instance: generic-device-plugin

patches:
  - path: usb.yaml
