---
apiVersion: v2
type: application
name: loki
version: 0.0.0  # unused
appVersion: 0.0.0  # unused
dependencies:
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 2.16.0
    condition: loki.enabled
