---
apiVersion: v1
kind: Service
metadata:
  name: unpoller

spec:
  type: ClusterIP
  ipFamilyPolicy: SingleStack

  ports:
  - port: 9130
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: unpoller
    app.kubernetes.io/instance: unpoller