---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: op-token
  namespace: default
spec:
  encryptedData:
    token: AgCi1M52VpQyVY+KOdby+lAM4uq7I2eiWb05JlPKqV3SrBZM96MPdOf5zXh6UMy7km4tNWoXhUohJgyeF7log/0qkCikBXyqsczj2XvvAm6H5XBurYmseAAWmn7O4RMoihLUq6yPb5B7/bjvoCyHw09J3sJ5vGOdMygeEMkEp8QPFS5/oF9+rs/9HdthGq6tGLHE9maEtK6580tmnoP6UU7C2bHespYOEuK09V2hoZNQgsYTG23wSiuj+e/MmcCBzd0UX6vxrENy9ZsmBrE4PTrGM7QpMu8+3IQ7J98p4gboZK16smylafzn5UYHBRjru/dKKk7hUxw7+ezlDe9BdXHyrt/Fg8c2bS7o0+YmRs1G+6DlCTvJRf/MUUmjrrYO+KbOQjuoTjOw4zHa0wSPVxGaK02UUmThzidaGs3NHf5TriX2PfGh2NMs6FeYd2X0et1ZjtW/4mkyAwRR5Vl4iCewNTFZYjIXzhAyiuMRRYGoU9N8eoTiHxx4ArF00t7wiBV/cHBqo4JVBpo+XEoKWnd2R5UWdJ5e5GfvbghDpZFyls7N0TPcdQryGnxbQE3s98AGyPeWJ2YA2lNfKzUGVIK+V7yUutMaZx/w+kQ/kYKF6l441xv6K0fLBaklR+eNJ+P4smtrIQDKQQoXP2yXWeXXC5QCu3VYhWzgxfaFiNEB/oZzsj6MbWIb/e2XIOiZEaL5pNLBSeaqmO3nmttDeWoOIJkPq5irlwQ2jgDEcaQkl2LwVLYiJtNxMykGqjZtlGhFfsK5+OyKQUK5iGw6fb88Ewl40qJh6yLV3s8KVgjBBN1P/xP0avx3Nlh5o8ToFmrGTck8DsZHcMAAHUYYkMWpJy99SvKzqXoweYyYUqfwpfPWewOnXU1RpEXPIFNVPhInKxFh1cKpgTGX6VpVREgIqVckYgjkmJU6/tjyE8ZyOo+WbEHMk94nafTRDWPtfosECH6YCyhmfLxc9xxNlu84JFambQUbv6R6jQ1EynTjLSI1QN6U6vHNO+TL6+Jemb9gnzkTrmivt7fLBFQhgUNKKyfSvnXwBZmM42Z6bowiq08vjEy60D4qZDpIpE0w4VEVbuiH88mY/K3XbrzHTAIOk0itEH/RDi9JuT9O8cw/OkBHsHaCiy8Nn1mGPd5oB37lFUwYMv0/rUwvpIWBi2sQbISZRei9r2nUdRKPCa/ks9VoY/Uynxot39udH/V3kODqyMg/++vGMG4VOYsZO6qaF5U89Y/sS/Q9O8ORN5dF/ZScLCpCaZX4gWb3elIk6+ZvgiJb9CFDcU1oglffkUl7vfhLI8RVk88zeC50s0hE19G0BkBat4BjzYU1S2YaCyw8hMGr1t/tRVXJKw/zxfyTweaGjFsljyoeJ5C5VmbPJyHvEvF1u58se7+k4KwSCVOWqr/Bva7wKx0cpvnGWYFJcrZ5sDf0RIVeeQTLgcecfeYHAAdSeiqXM8MPvNCMNeLvAddh44f11K/6Oj1sp5Zy69g/5g3dXzpetF7B71KtVI5Q4lmIfJcFJ6IiUhHh3+elXmRNTLKzKW1L3AUUHvEZW1Q=
  template:
    metadata:
      creationTimestamp: null
      name: op-token
      namespace: default
    type: Opaque
