---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: op-token
  namespace: default
spec:
  encryptedData:
    token: AgCHM7A69m0g7Wu5ptBb0fcZVmyTfE8x+bVtqFRmf088UGylqYm1xXk89awMa3753zOSWQqSgV8E+6j9YLn2naRvVvXCOy2BSAzdcvl3JfuY6Ty+R5i5C+LL0/XXjZXcHL12p6t+SZfzbwk0a2vosiPHnzP/mnAgJQ9sAiSfEEz4yy7aOPfhSwhU9XtC09V4pMKGbVFHJipzwwF4yottgqHaSxLu3WGRMENz9GYacpcNvBc6EXxt98PdgvaMY7LxexNcA3lDoLAKpTJj4HlhmeAq+usHRbmlu0Ui+TrZtHWbLmxY2mLXly7+IpMC5rELND7AJwug+oKg5HJetWGVZzYtdYBy/QsjsVLTliGINRhUZxUm4YmyhTUbdC3RflZLMXyzvqIF7Qxsq8G5SOIzPArVpbyugvtjWTeKvj5dK93IUkTTGNP1PubpDQdSK1yeMD0CPl0/R/1qCBCt9cxY2C97EcQDV30r+K8T2dm3rtjmRDFxkQGweV9E2kDMwIpi3byea1oAKL+pwxyY0fQzJmWSAg2WDdNrKdIw8iFx0vr0deJ59qbzjuVLJsdod1AHocTaVLMsZPOyR3iSWqI7cFZD9z6yMtL8ufhqmTlTsFPnSeWg7ht6OxabW+s6BuNL0Kumb7IN+CLNKZpQA/ntzC9SLsp+aXQwtUZv05qDLb1SPuP6eSAWhGynOKJfQHnF4Nt0n1wlZF0RAE1t5bdWA/aeSrrTJMDMsXrj4a4x+682RjxmLtdtHZVJhAAn5CzpoBgfoaC9jKQTdN37cUaX84mCts0ArT6ywshU/aL2b8QuNVyPjN5VUScM2JeC2prMGtAespFtOW+SeSA7Mvkg6iB3+fDGGfSP6af1iJdAUNE7L5xYicrVQrxcfKihO1spkxqB7AkDDTO4IuyC1n0X+vL4pdkSPypPtijLMIP2b1tJ1NU5lwNQDpvl5Q63dk0q4Cadz/FFF3s4UaFzcrBpHYYfeer2pFudNNNnNBwygd9VlOLi6pO14YY5vHz4eOWSZoNf1sZDAcyHpUEwT7YRbnFAJBsRzHeMxDhMM3hAcANfRDP02xzW7hnLNws271vJhOQhIxfvCAAyXr487QOoMiUY/QAwzUlbnIMvFsgHXnSOITRQlzwk8IUEkMVO4TShgTW4kqgPK94rOO/7W1CzQ3T/Q0CFr1tlufPbFEE151HYf7icZKXnpy16RhKr9HQkSFgq2emIZqaW58FgfTirKYKJFnyYWcjFFEwTGUuidwOJiGaikt5XZeHj0htbiJe1ZB/H100ke95DaVjIwxMgyM44UulJHruoifpyQJ5rxqlg45h1cf49pkWd4wEr0JU4tgNm/qWuWwiPjo/VXRIIpxEqUqm5HRnMG5pAlMXlc5Fa8k4h+w0nAJRruZMjTVXei89o9d4dNi0RDtphPXLXrFIrwVb/2TxXVARrh4BMRIa7PghfZCjFz9ufqIn3pGMw7UgXWo6WWH5+rPPPFTpmUeCtu1+ptDX54Pb7dCLclw+pOEuwuDRK23B+xnecpTkQOIAYzBIPTY15d/iW2XTh95Jrb0Y=
  template:
    metadata:
      creationTimestamp: null
      name: op-token
      namespace: default
    type: Opaque
