---
apiVersion: v1
data:
  CREATE_TUN_DEVICE: "true"
  LOCAL_NETWORK: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  OPENVPN_CONFIG: atl-001
  OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
  OPENVPN_PROVIDER: PRIVADO
  TRANSMISSION_SPEED_LIMIT_UP: "4096"
  TRANSMISSION_HOME: /config/transmission-home
kind: ConfigMap
metadata:
  name: transmission-openvpn
  namespace: default
