apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: haus-mcp-zoom

resources:
  - manifests/namespace.yaml
  - manifests/redis.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/onepassworditem-env.yaml
  - manifests/onepassworditem-ghcr-pull.yaml

labels:
  - pairs:
      app.kubernetes.io/name: haus-mcp-zoom
      app.kubernetes.io/instance: haus-mcp-zoom

images:
  - name: ghcr.io/dels78/haus-mcp-zoom
    newTag: "5de0c20"
