---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homarr-config
  labels:
    app.kubernetes.io/name: homarr
    app.kubernetes.io/instance: homarr
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "999Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homarr-icons
  labels:
    app.kubernetes.io/name: homarr
    app.kubernetes.io/instance: homarr
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "999Gi"