---
kube-prometheus-stack:
  enabled: true

  # addtionnal prometheus rules
  additionalPrometheusRulesMap:
    rule-name:
      groups:
        - name: general
          rules:
            - alert: DNSProbeFailure
              expr: probe_success{instance="<path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/whpihnlm7fc3tcuyi2or2xxyjq#adguard-dns-ip>"}==0
              for: 1m

  #  grafana
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.delisle.me
    persistence:
      enabled: true
      type: pvc
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      finalizers:
        - kubernetes.io/pvc-protection

  #  prometheus
  prometheus:
    ingress:
      enabled: true
      hosts:
        - prometheus.delisle.me
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: homeassistant
          metrics_path: /api/prometheus
          scheme: https
          scrape_interval: 60s
          static_configs:
            - targets: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/3jlesbodtkawtkazo3gd2lfa2a#homeassistant_target>
          authorization:
            credentials: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/3jlesbodtkawtkazo3gd2lfa2a#homeassistant_credentials>
        - job_name: 'blackbox-dns-monitor'
          scrape_interval: 5s
          metrics_path: /probe
          relabel_configs:
            # Populate domain label with domain portion of __address__
            - source_labels: [__address__]
              regex: (.*):.*$
              replacement: $1
              target_label: domain
            # Populate instance label with dns server IP portion of __address__
            - source_labels: [__address__]
              regex: .*:(.*)$
              replacement: $1
              target_label: instance
            # Populate module URL parameter with domain portion of __address__
            # This is a parameter passed to the blackbox exporter
            - source_labels: [domain]
              target_label: __param_module
            # Populate target URL parameter with dns server IP
            - source_labels: [instance]
              target_label: __param_target
            # Populate __address__ with the address of the blackbox exporter to hit
            - target_label: __address__
              replacement: blackbox-exporter-prometheus-blackbox-exporter:9115

          static_configs:
            - targets:
                - www.google.com:<path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/whpihnlm7fc3tcuyi2or2xxyjq#adguard-dns-ip>
                - www.microsoft.com:<path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/whpihnlm7fc3tcuyi2or2xxyjq#adguard-dns-ip>
                - www.google.com:8.8.8.8
                - www.microsoft.com:8.8.8.8
                - www.google.com:1.1.1.1
                - www.microsoft.com:1.1.1.1
                - www.google.com:9.9.9.9
                - www.microsoft.com:9.9.9.9

  #  alertmanager
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - alertmanager.delisle.me

  # k3s specific
  kubeApiServer:
    enabled: true
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeEtcd:
    enabled: false
