---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: system-upgrade

resources:
  # renovate: datasource=docker image=rancher/system-upgrade-controller
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.11.0/crd.yaml
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.11.0/system-upgrade-controller.yaml
  - k3s-upgrade-plans.yaml
images:
  - name: rancher/system-upgrade-controller
    newTag: v0.13.1
commonLabels:
  app.kubernetes.io/name: system-upgrade-controller
  app.kubernetes.io/instance: system-upgrade-controller

patches:
  - target:
      kind: Plan
      name: k3s-*
    patch: |-
      - op: replace
        path: /spec/version
        # renovate: datasource=github-releases depName=k3s-io/k3s
        value: v1.20.2+k3s1
