---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

resources:
  - manifests/deployment.yaml
  - manifests/cloudflared-external-secret.yaml

images:
  - name: cloudflaredimage
    newName: cloudflare/cloudflared
    newTag: "2024.8.2"

commonLabels:
  app.kubernetes.io/instance: cloudflared
  app.kubernetes.io/name: cloudflared
