apiVersion: v1
kind: Secret
metadata:
  name: origin-cert
  namespace: default
type: Opaque
stringData:
  tls.crt: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/5yvc5i6qepbfdh63qnhpqaligq#tls.crt>
  tls.key: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/5yvc5i6qepbfdh63qnhpqaligq#tls.key>
