---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home.dels.info
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`home.dels.info`)
      services:
        - name: home-dels-info
          port: 8123
      middlewares:
        - name: security
  tls:
    secretName: origin-cert
    options:
      name: tlsoptions
