---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: home.dels.info
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`home.dels.info`)
      services:
        - name: home-dels-info
          port: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/iuz4hyi26smueirmdvyndrzw2i#port>
  tls:
    secretName: origin-cert
