---
kind: Service
apiVersion: v1
metadata:
  name: home-dels-info
  namespace: default
spec:
  type: ExternalName
  externalName: home-assistant.home-automation.svc.cluster.local
  ports:
    - name: http
      port: 8123
      targetPort: 8123
