apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/configmap.yaml
  - manifests/ingress.yaml
