---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - manifests/serviceaccount.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/configmap.yaml
  - manifests/ingress.yaml

images:
  - name: transmissionimage
    newName: haugene/transmission-openvpn
    # renovate: datasource=docker image=haugene/transmission-openvpn
    newTag: "master"

commonLabels:
  app.kubernetes.io/instance: transmission-openvpn
  app.kubernetes.io/name: transmission-openvpn
