---
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

namespace: retool

resources:
  - manifests/namespace.yaml
  - manifests/license-secret.yaml

helmCharts:
  - name: retool
    releaseName: "retool"
    repo: https://charts.retool.com
    version: 6.4.9
    namespace: retool
    includeCRDs: true
    valuesFile: ./values.yaml
