---
apiVersion: v2
type: application
name: grafana
version: 0.0.0  # unused
appVersion: 0.0.0  # unused
dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 6.59.0
    condition: grafana.enabled
