---
robusta:
  enabled: true
  clusterName: homeops
  isSmallCluster: true
  globalConfig:
    signing_key: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/46gjjkrum5jogfxzpejrrd6bam#signing_key>
    account_id: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/46gjjkrum5jogfxzpejrrd6bam#account_id>
  sinksConfig:
    - slack_sink:
        name: main_slack_sink
        slack_channel: monitoring
        api_key: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/46gjjkrum5jogfxzpejrrd6bam#slack_sink_api_key>
    - robusta_sink:
        name: robusta_ui_sink
        token: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/46gjjkrum5jogfxzpejrrd6bam#robusta_sink_token>
  enablePrometheusStack: true
  enablePlatformPlaybooks: true
  runner:
    sendAdditionalTelemetry: false
  rsa:
    private: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/46gjjkrum5jogfxzpejrrd6bam#rsa_private>
    public: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/46gjjkrum5jogfxzpejrrd6bam#rsa_public>
