---
robusta:
  #  values for kube-prometheus-stack
  kube-prometheus-stack:
    #  grafana ingress
    grafana:
      ingress:
        enabled: true
        hosts:
          - grafana.delisle.me
    #  prometheus
    prometheus:
      ingress:
        enabled: true
        hosts:
          - prometheus.delisle.me
      prometheusSpec:
        additionalScrapeConfigsSecret:
          enabled: true
          name: prometheus-additional-scrape-configs
          key: additional-scrape-configs.yaml
    #  alertmanager
    alertmanager:
      ingress:
        enabled: true
        hosts:
          - alertmanager.delisle.me

    # k3s specific
    kubeApiServer:
      enabled: true
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
