---
robusta:
  #  values for kube-prometheus-stack
  kube-prometheus-stack:
    #  grafana ingress
    grafana:
      ingress:
        enabled: true
        hosts:
          - grafana.delisle.me
    #  prometheus
    prometheus:
      ingress:
        enabled: true
        hosts:
          - prometheus.delisle.me
      prometheusSpec:
        additionalScrapeConfigs:
            - job_name: "homeassistant"
              scrape_interval: 60s
              metrics_path: /api/prometheus
              # Long-Lived Access Token
              authorization:
                credentials: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI3NDRjZDQ2ZmNiMWM0NmU4ODlmODg2MjRjNGNmNWI4OCIsImlhdCI6MTY2MTQ3NTk3OCwiZXhwIjoxOTc2ODM1OTc4fQ.v9oy-1Uiu-7kuX9vxvr4qmYhE2OshyH4TCJojoSeKw0"
              scheme: https
              static_configs:
                - targets: ['home.dels.info']
    #  alertmanager
    alertmanager:
      ingress:
        enabled: true
        hosts:
          - alertmanager.delisle.me
