apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: haus-mcp-zoom-secrets
  namespace: haus-mcp-zoom
  labels:
    app.kubernetes.io/name: haus-mcp-zoom
    app.kubernetes.io/component: server
spec:
  itemPath: "vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/ngdfhdsiv6w5d743wkbvqurwsi"
