---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 3000
    auth_name: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/fovonhsxgtfo7wgktjcktdmdne#auth_name>
    auth_pass: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/fovonhsxgtfo7wgktjcktdmdne#password>
    language: "en"
    rlimit_nofile: 0
    rlimit_nproc: 0
    log_file: ""
    log_syslog: false
    log_syslog_srv: ""
    pid_file: ""
    verbose: false
