---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-pv
  namespace: adguard
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/adguard"
