---
# kustomize build . >argocd-deploy.yml
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.7.3
  - namespace.yaml

images:
  - name: ghcr.io/crumbhole/argocd-lovely-plugin-cmp
    newTag: 0.19.1

patches:
  - path: argo-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-lovely-plugin.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
