apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://github.com/rancher/system-upgrade-controller/blob/master/manifests/system-upgrade-controller.yaml
  - k3s-upgrade-plans.yaml