---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: system-upgrade

resources:
  # renovate: datasource=docker image=rancher/system-upgrade-controller
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.10.0/crd.yaml
  - https://github.com/rancher/system-upgrade-controller?ref=v0.11.0
  - k3s-upgrade-plans.yaml
images:
  - name: rancher/system-upgrade-controller
    newTag: v0.11.0
commonLabels:
  app.kubernetes.io/name: system-upgrade-controller
  app.kubernetes.io/instance: system-upgrade-controller
patches:
  # Delete namespace resource
  - patch: |
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{install.upgrade_controller.namespace}}
    target:
      kind: Namespace
