---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflared
type: Opaque
stringData:
  token: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/oulw7jxwadwafkfx7ozqiibv34#cloudflared-token>
