---
apiVersion: v1
kind: Secret
metadata:
  name: config-cloudflare-ddns
  namespace: cloudflare-ddns
type: Opaque
stringData:
  config.json: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/oulw7jxwadwafkfx7ozqiibv34#config.json>
