---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: external-secrets
  
  annotations:
    notifications.argoproj.io/subscribe.slack: github
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/dels78/homeops.git
    targetRevision: HEAD
    path: apps/external-secrets/

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true