---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: nfs-subdir-external-provisioner

  annotations:
    # notifications.argoproj.io/subscribe.on-sync-succeeded.slack: github
    notifications.argoproj.io/subscribe.on-sync-failed.slack: github
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: github
    notifications.argoproj.io/subscribe.on-health-degraded.slack: github
    notifications.argoproj.io/subscribe.on-deployed.slack: github
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    # yamllint disable-line rule:line-length
    repoURL: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/'
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      valueFiles:
        - values.yaml
      values: |-
        nfs:
          server: 192.168.1.252
          path: /volume1/k3s
        storageClass:
          name: nfs-client
          defaultClass: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
