---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: robusta

  annotations:
    # notifications.argoproj.io/subscribe.on-sync-succeeded.slack: github
    notifications.argoproj.io/subscribe.on-sync-failed.slack: github
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: github
    notifications.argoproj.io/subscribe.on-health-degraded.slack: github
    notifications.argoproj.io/subscribe.on-deployed.slack: github
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/dels78/homeops.git
    targetRevision: HEAD
    path: apps/robusta/
    plugin:
      name: argocd-lovely-plugin

  destination:
    server: https://kubernetes.default.svc
    namespace: robusta

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
