---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: unpoller

  annotations:
    # notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argo
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argo
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argo
    notifications.argoproj.io/subscribe.on-deployed.slack: argo
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/dels78/homeops.git
    targetRevision: HEAD
    path: workload/apps/unpoller/
    plugin:
      name: argocd-lovely-plugin
      name: argocd-lovely-plugin

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
