---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml

images:
  - name: yopassimage
    newName: jhaals/yopass
    newTag: "11.19.1"

commonLabels:
  app.kubernetes.io/instance: yopass
  app.kubernetes.io/name: yopass
