---
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

namespace: default

resources:
  - manifests/sealedsecret.yaml
  - manifests/serviceaccount.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/configmap.yaml
  - manifests/ingress.yaml

images:
  - name: transmissionimage
    newName: haugene/transmission-openvpn
    # renovate: datasource=docker image=haugene/transmission-openvpn
    newTag: "5.3"

commonLabels:
  app.kubernetes.io/instance: transmission-openvpn
  app.kubernetes.io/name: transmission-openvpn

configMapGenerator:
  - name: transmission-openvpn
    behavior: merge
    literals:
      - OPENVPN_CONFIG=mia-006
