---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns-udp
  namespace: adguard
spec:
  selector:
    app.kubernetes.io/name: adguard
  ports:
    - protocol: UDP
      port: 53
      targetPort: dns-udp
      name: dns-udp
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/whpihnlm7fc3tcuyi2or2xxyjq#adguard-dns-ip>
