---
apiVersion: v1
kind: Service
metadata:
  name: adguard-exporter
  namespace: adguard
spec:
  selector:
    app.kubernetes.io/name: adguard-exporter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: metrics
  type: ClusterIP
  ipFamilyPolicy: SingleStack
