---
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

namespace: cloudflare-ddns

resources:
  - manifests/config-secret.yaml
  - manifests/deployment.yaml

images:
  - name: cloudflare-ddns-image
    newName: timothyjmiller/cloudflare-ddns
    # renovate: datasource=docker image=timothyjmiller/cloudflare-ddns
    digest: sha256:2187e122660d6a2d451ef7c53fd4805c133133f4f47552256352c1e2a7f49ee2

labels:
  - pairs:
      app.kubernetes.io/instance: cloudflare-ddns
      app.kubernetes.io/name: cloudflare-ddns
