---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-ddns

resources:
  - manifests/config-secret.yaml
  - manifests/deployment.yaml

images:
  - name: cloudflare-ddns-image
    newName: timothyjmiller/cloudflare-ddns
    # renovate: datasource=docker image=timothyjmiller/cloudflare-ddns
    digest: sha256:9f55e3ad0e88bee4b74c178c82fa622db14ed24b9e723d80701bccb00231a9ee

commonLabels:
  app.kubernetes.io/instance: cloudflare-ddns
  app.kubernetes.io/name: cloudflare-ddns
