---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - github.com/metallb/metallb/tree/cb3bcb8da20e9b91280c09a4b7a00adf9ef2a748/config/native
  - config.yaml
