---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki

spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      volumes:
        - name: storage
          emptyDir: null
          nfs:
            path: /volume1/loki
            server: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/jajjjswjty5goro6qk5427bdmm#ip>
