---
loki:
  enabled: true
  #  actual values for loki
  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
    storageConfig:
      filesystem:
        directory: '/data'
  singleBinary:
    replicas: 1
    extraVolumeMounts:
      - name: loki-data
        mountPath: /data
    extraVolumes:
      - name: loki-data
        nfs:
          path: /volume1/loki
          server: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/jajjjswjty5goro6qk5427bdmm#ip>
