---
loki:
  enabled: true

  #  actual values for loki
  loki:
    isDefault: false
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'

  singleBinary:
    replicas: 1

  # disable grafana sidecar
  grafana:
    sidecar:
      datasources:
        enabled: false
