---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ha-token
  namespace: robusta
spec:
  encryptedData:
    ha-token: AgA433IOnga1TbYs0xAxewldqI5/F2Kf2HgXMZM47o1E5mmSaNU824NOQYIM+P8NALw89XbkS0hWEcVck1NtNYHrmXqSXea258shlS6gvUoxoxXkfZ0H8UHElrr4brpkY4j52p6pltDj6icxb9ebDcI8l57xON/BDa7JjNpcdgM9PflmEGXQVFaKrKC1xMJJASr435aAyvGvooNnokfW+bqytCdDj0jSIoEzVsMYqpE8dcPNJ9OwULAPMkfZ+MeA2IzujRl5zGVja7c8fxDTzrCVYkiRnDfmvxL7+O+UcYC98bpAwGoWxL5o/ur8kMZfHM6t0jH6p9OQDM92uggvUe9FkcBx1bjy7Snj/f8kDpKv/6j3f2+Kz5ur+u4HP/wteGSBOTHuaQAUAlPv6DxaPLWFT/tDEdE0GHHXofQ1CPgTKZuVggodpHxvJnhL7prXQaNRyJq4r0Tv+5KSroSSZE8Vi9J1LuS0F0pBM9qYlcKtEVC7lcxSOhcntDSiUSEZzT5pQU1CzOeQhjHfjgfZy3woLkcyFpGoCUbDqwEhJ89UAS3+6DCBglQBbduWD1gSD+mgJ9F4dv8+cNq77Aqj42A7TX0p2AWggk0w/6TWOz9B/oVukddoRWjb5jFoLN5jboYGNk8Kap4CsAolJMC30KTB8b02s94yYEQQfWCa0QpmyTyjZiWq1esz2G7qVmlh7oBOrHrzBRfSF5ig6TcLiCZoxaAhBOQROKMs1LR39XHZ1N8xthyUPZTtWJxN1f/TAHI+vnPPY2iaBHxeK1NO6fPtnouhYji5dA+yyI3QpB+XwKMzwRnAdb4LCvKWC15OLnNvX+km33DebW3RsRvM5vuSUfJic7bL4A/Fb6U5RW54w6P1tJd7949t3xn2olYVI7+nGMoLGi7j2Z6N8U4W8aC/CjVuad78ZftzsQzcSUiDxVzZrm5Mh1o=
  template:
    metadata:
      creationTimestamp: null
      name: ha-token
      namespace: robusta
    type: Opaque
