---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgBKA1Bla53qOTrfv89vIhdN4Cph8jXv9tyCGvKA42QEiAncbaLsyetulO3Rdyh1TfpVoByh+VW9cXF3U4tqrDz60EfnfwOMAmGxP1LX17eOaAiJ3+3TSPZETT8oAzy1ZDeYSfKkas6K2UloWy9M47q5fCW7kK88ZHS+zrENiw/BtliYe+qnFGaeOp6Wk3ZWam1cJgY9Ghi66eVz3KW8sFzLbLZjxLaMd3gXSx8VdlNV/mW+TyrNQrLy6XdBrd5YOuuvGHbpAJMFgTMIwrTfEC34j2FhK+T1F0ALUJl4ThHvAlOxfJkPDwhlN9vM2GUXh16ICkrJ+DLOlylTcH3wTwK9jASRHmf8uQAk2hnTuqJbld9NAh0BPKxReCxtbivsl0GRdDsrOKfSMjwU3fYc8VpL7boELJpwHYRG2eJISnzB5auab+l0QxG1lIv4gpqxvy89FH/DWOYnqPiP0qfSdi8NoKDl+I+69TBqBXgRS5mUcYGNlnaz5dT32XfToI7uTrAGE7IkpeGFHVcP33mI6QvqSznJ/TjHHLsY9sYf3Tm7SFmk9rumc4z6/waO4fK4QOfY1Mtstlj+qmX0uGqUhlnY5dI0k+4i/ylurKJAEaGec3ExNvOtx1n5QG8MJu5nfvVdGl7rIb2O07swsgkZg9XGYcdpO3TQHaJdKpDS3d0FiERtFtjXnOnL1/j0/adnU7YlZLjdQR8jUC98PKO/G/T14004EL+flyNLsbRTqLiapF5W/89NLK4ckoCEfBSERtgINunYFfC1
  template:
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
