---
# This is a template for the Ring MQTT secret
# Replace RING_REFRESH_TOKEN_HERE with your actual Ring refresh token
# Then seal it using kubeseal:
# kubectl create secret generic ring-mqtt-secret \
#   --from-literal=ring-token="YOUR_RING_TOKEN_HERE" \
#   --namespace=home-automation \
#   --dry-run=client -o yaml | \
#   kubeseal --format=yaml > sealedsecret-ring-mqtt.yaml
#
# Example (do not use this token, it's from the backup):
# ring-token: "eyJhbGciOiJSUzI1NiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiNGRjODQyZGIiLCJ0eXAiOiJKV1QifQ..."
apiVersion: v1
kind: Secret
metadata:
  name: ring-mqtt-secret
  namespace: home-automation
type: Opaque
stringData:
  ring-token: "RING_REFRESH_TOKEN_HERE"

