---
vm:

  enabled: true

  nameOverride: vm
  fullnameOverride: vm
  argocdReleaseOverride: victoriametrics
  defaultRules:
    create: true
    rules:
      etcd: false
      general: true
      k8s: true
      kubeApiserver: true
      kubeApiserverAvailability: true
      kubeApiserverBurnrate: true
      kubeApiserverHistogram: true
      kubeApiserverSlos: true
      kubelet: true
      kubePrometheusGeneral: true
      kubePrometheusNodeRecording: true
      kubernetesApps: true
      kubernetesResources: true
      kubernetesStorage: true
      kubernetesSystem: true
      kubeScheduler: false
      kubeStateMetrics: true
      network: true
      node: true
      vmagent: true
      vmsingle: true
      vmhealth: true
      alertmanager: true
  vmsingle:
    ingress:
      enabled: true
      hosts:
        - victoriametrics.delisle.me
  grafana:
    enabled: true
    persistence:
      type: pvc
      enabled: true
    ingress:
      enabled: true
      hosts:
        - grafana.delisle.me
  vmagent:
    spec:
      inlineScrapeConfig: |
        - job_name: "prometheus"
            static_configs:
            - targets: ["localhost:9090"]
        - job_name: homeassistant
            metrics_path: /api/prometheus
            scheme: https
            scrape_interval: 60s
            static_configs:
              - targets: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/3jlesbodtkawtkazo3gd2lfa2a#homeassistant_target>
            authorization:
              credentials: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/3jlesbodtkawtkazo3gd2lfa2a#homeassistant_credentials>
        - job_name: 'blackbox-dns-monitor'
            scrape_interval: 5s
            metrics_path: /probe
            relabel_configs:
              # Populate domain label with domain portion of __address__
              - source_labels: [__address__]
                regex: (.*):.*$
                replacement: $1
                target_label: domain
              # Populate instance label with dns server IP portion of __address__
              - source_labels: [__address__]
                regex: .*:(.*)$
                replacement: $1
                target_label: instance
              # Populate module URL parameter with domain portion of __address__
              # This is a parameter passed to the blackbox exporter
              - source_labels: [domain]
                target_label: __param_module
              # Populate target URL parameter with dns server IP
              - source_labels: [instance]
                target_label: __param_target
              # Populate __address__ with the address of the blackbox exporter to hit
              - target_label: __address__
                replacement: blackbox-exporter-prometheus-blackbox-exporter:9115
            static_configs:
              - targets:
                  - www.google.com:<path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/whpihnlm7fc3tcuyi2or2xxyjq#adguard-dns-ip>
                  - www.microsoft.com:<path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/whpihnlm7fc3tcuyi2or2xxyjq#adguard-dns-ip>
                  - www.google.com:8.8.8.8
                  - www.microsoft.com:8.8.8.8
                  - www.google.com:1.1.1.1
                  - www.microsoft.com:1.1.1.1
                  - www.google.com:9.9.9.9
                  - www.microsoft.com:9.9.9.9
