argo-cd:
  enabled: true
  
  ## Argo Configs
  configs:
    # Argo CD configuration parameters
    ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
    params:
      ## Server properties
      # -- Run server without TLS
      server.insecure: true
  
  ## Dex
  dex:
    # -- Enable dex
    enabled: false
  
  
  ## Notifications controller
  notifications:
    # -- Enable notifications controller
    enabled: true
  
    # -- Configures notification services such as slack, email or custom webhook
    # @default -- See [values.yaml]
    ## For more information: https://argocd-notifications.readthedocs.io/en/stable/services/overview/
    notifiers:
      service.slack: |
        token: $slack-token
  
