apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - manifests/deployment.yaml
  - manifests/service.yaml

images:
  - name: unpollerimage
    newName: ghcr.io/unpoller/unpoller
    newTag: "v2.7.10"

commonLabels:
  app.kubernetes.io/instance: unpoller
  app.kubernetes.io/name: unpoller